### ISSUE TITLE
Fatal Exception on nearly succesfully running the code

### ISSUE THREAD

**Issue by jan0w123** [alessandromatera/SDM230-emulator-growatt-esp-mqtt#4]
Hello together, im running the code on an NodeMCU Amica ESP8266 board, the connection to the WiFi network suceeded and the data transfer via mqtt works perfectly. 
As soon as I get data transfer with the inverter the ESP runs into following exception:
`xception (0):
epc1=0x40207ac8 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

>>>stack>>>

ctx: sys
sp: 3fffebe0 end: 3fffffb0 offset: 0190
3fffed70:  40106614 3ffee118 3ffee860 00000000  
3fffed80:  00000001 00000000 c0037035 00000030  
3fffed90:  000000a6 00000206 00000001 c0037035  
3fffeda0:  00000078 00000117 00000001 c0037035  
3fffedb0:  00000000 00000001 00000000 40100970  
3fffedc0:  00000020 000001bb 00000001 40100970  
3fffedd0:  00000020 4010598f 3ffeca00 00000022  
3fffede0:  3fffc200 401008ac 3fffc258 4000050c  
3fffedf0:  4000437d 00000030 00000010 ffffffff  
...`

I tried several settings and versions of the IDE too, but no succes so far.
The inverter still shows the error "401" which means no connection to the meter.
In some cases the Error disappears for fragments of a second, bevore the error occures. 
So I assume the the communication to the inverte an MQTT works correct.

Is it a common fault?

Greets

==> EIDT:

Now its running. But it seems like my inverter is awaiting other adresses for the measurements, its an SPH4000 inverter.
The meter sold to this inverter is th SDM630 instead of the SDM230, so I have to modify the adresses to where the data has to been sent.

**Comment by AlbertWeterings** [comment]
@jan0w123 I found your message here. Can you tell me what you have changed to alessandro's code to make it work with the SPH 4000. And if you found an even better way to get same done I'm interested.  I'm working on using this code with a SPH 3600.

@alessandromatera Great work this code. As I see read this we only have to send negative values to ramp down the inverter right? Or can we also send positive values if we want the inverter to produce more power?

I'm asking as I have a bit a strange setup. I'm using a battery powered inverter to power my home of grid  but there is a field with solar panels and a Growatt inverter connected to the grid. on the grid side there is also a hot water boiler and two chargers, those devices are heating and charging only with excess energy provided by the Growatt. I can modulate these devices so I do not export to the grid. But often at the end of the day batteries are full boiler is on temperature and the Growatt is sending energy to the grid. I want to use you're code to limit at these moments the Growatt to not sending anything to the grid.

**Comment by alessandromatera** [comment]
Thanks @AlbertWeterings!

In my growatt inverter I use the power limit export function to limit the output to the grid by sending negative values to the inverter. If you send positive values the inverter will assume that you're not exporting so it will try to produce as much power as possible to cover your home consumption.

In the inverter parameters you can also set the maximum export limit in watt. The only thing I noticed is that, even If I set -200W, if the actual power from the grid is within 0W and -200W the output of the inverter does not change, meaning that it does not follow strictly the -200W or neither it would increase power export if the grid is at -100W for example. Indeed it's something that makes sense if you look at the original scope of this feature "allowing maximum export to a certain amount"; then if it's exporting lower, but still exporting (meaning grids power is < -0W), it will stay put.

Ciao

**Comment by AlbertWeterings** [comment]
@alessandromatera Thanks for your answer. As in my setup the inverter should only limit output if it goes above the Boiler and chargers usage I am going to send a calculated value to the inverter. Do you know what happens if the inverter is limited and you send repeatedly 0 watt? Does it then decrease the limit or stay's at the limited value? that is important for me to come out of the limiting state. If I have to send positive values I have to change my code ;-)

**Comment by alessandromatera** [comment]
Honestly I don't know :) You have to test it out

Cheers

Alessandro

**Comment by AlbertWeterings** [comment]
I see my Growatt do different requests, it looks like it is probing 3 meters. Currently I only respond to the one starting with 02 do you have any idea what the other requests are for?
                                   
[45553ms] Received: 02 04 00 00 00 12 70 34
[45634ms] Received: 01 04 00 00 00 14 F0 05
[45715ms] Received: 03 03 20 00 00 0A CF EF
